apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: v29v42fex-python-gitops
  description: This is GitOps manifest for v29v42fex-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=v29v42fex-python
    backstage.io/kubernetes-id: v29v42fex-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: v29v42fex-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:v29v42fex-python
